# Generated by Django 3.2.5 on 2021-07-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210724_1251'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='api_user',
        ),
    ]
