# Generated by Django 3.2.5 on 2021-07-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_account_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table=None,
        ),
    ]
