# Generated by Django 3.2.5 on 2021-07-29 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_account_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='api_user',
        ),
    ]
